### PR TITLE
Fix #5

### LINKED ISSUE #5: config.footprints.prefix is not affecting models routes
Setting `config.footprints.prefix = '/api/v1'` doesn't affect footprint routes paths for models.

### PR DESCRIPTION
**Pull request by zuker**

### CODE REVIEW

**Comment by jvkassi** [comment]
Can this be merged ?

**Comment by jaumard** [comment]
@tjwebb little up here because a lot of user have this issue (in fact every user who use footprints) thanks :)

**Comment by tjwebb** [comment]
Yikes, sorry, I missed this one. Looks good to me.

@jaumard if I miss something feel free to merge things if you think they look okay.

**Comment by tjwebb** [comment]
This may also resolve https://github.com/trailsjs/trails/issues/117

**Comment by jaumard** [comment]
Yes I think it also fix trailsjs/trails#117. @tjwebb no problem I'm trying to merge PR when I can but I don't have rights on this repo, maybe it can be added to web server team.

**Pull request merged**
